name: prochat
description: "ProChat - Professional consultation platform"
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.18.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  fl_chart: 0.68.0
  google_fonts: 6.1.0
  shared_preferences: ^2.3.2
  path_provider: 2.1.4
  provider: ^6.1.2
  http: ^1.1.0
  uuid: ^4.0.0
  table_calendar: ^3.0.9
  image_picker: ^1.0.4
  share_plus: ^7.2.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  # Permissions for camera/microphone
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.4.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
