import '../models/app_models.dart';


class DummyDataService {
  static List<Expert> getExperts() {
    return [
      Expert(
        id: 'exp1',
        name: 'Dr. Sarah Johnson',
        nameArabic: 'د. سارة جونسون',
        email: 'sarah.j@chatpro.com',
        profileImage: "https://pixabay.com/get/gb463c8ac24ee253fb2afa8443273cef0454bafc517908164c95cbfdaef4b204bbcfabb158972f55d174879c0acaad0547d55bf66fff96303b7db8cea62efcbf8_1280.jpg",
        bio: 'Board-certified physician with 15 years of experience in family medicine. Specializing in preventive care and chronic disease management.',
        category: ExpertCategory.doctor,
        subcategories: ['General Medicine', 'Internal Medicine'],
        subcategoriesArabic: ['الطب العام', 'الطب الباطني'],
        languages: ['English', 'Arabic'],
        rating: 4.9,
        totalReviews: 342,
        pricePerMinute: 2.50,
        pricePerSession: 75.00,
        isAvailable: true,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 450)),
        regions: ['All'],
        todaySessionCount: 8,
        todayOnlineMinutes: 240,
        todayEarnings: 425.50,
        avgSessionRating: 4.8,
        customTimeEnabled: true,
        customPriceEnabled: true,
        sessionConfigs: [
          SessionConfig(
            id: 'sc1',
            name: '15min Quick Consultation',
            durationMinutes: 15,
            price: 10.0,
          ),
          SessionConfig(
            id: 'sc2',
            name: '30min Standard Session',
            durationMinutes: 30,
            price: 25.0,
          ),
        ],
        verificationStatus: VerificationStatus.verified,
        workExperience: 'MD from Harvard Medical School, 15 years in family medicine, former chief resident at Mass General.',
        qualifications: 'Board-certified in Family Medicine, Fellow of American Academy of Family Physicians',
        country: 'United States',
        verificationAttachments: [
          {
            'type': 'Document',
            'title': 'Medical License',
            'description': 'Board certification in Family Medicine',
            'url': 'medical_license.pdf'
          },
          {
            'type': 'Document',
            'title': 'Harvard Medical Degree',
            'description': 'MD from Harvard Medical School',
            'url': 'medical_degree.pdf'
          },
          {
            'type': 'Image',
            'title': 'Professional Photo',
            'description': 'Professional headshot for verification',
            'url': 'professional_photo.jpg'
          }
        ],
      ),
      Expert(
        id: 'exp2',
        name: 'Ahmed Al-Rashid',
        nameArabic: 'أحمد الراشد',
        email: 'ahmed.r@chatpro.com',
        profileImage: "https://pixabay.com/get/g91005b1ef8d8657afde26a0fb46b9db7a67708f62bbbe3d142c764b1e30725c6f8bd301a2525ff6dae36e3175dc9b8666e57d8bda2323f561e86500342a6ea70_1280.jpg",
        bio: 'Corporate lawyer with expertise in business contracts, intellectual property, and international law. Fluent in Arabic and English.',
        category: ExpertCategory.lawyer,
        subcategories: ['Corporate Law', 'Intellectual Property'],
        subcategoriesArabic: ['القانون التجاري', 'الملكية الفكرية'],
        languages: ['Arabic', 'English'],
        rating: 4.8,
        totalReviews: 198,
        pricePerMinute: 4.00,
        pricePerSession: 150.00,
        isAvailable: false,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 320)),
        regions: ['All'],
        todaySessionCount: 5,
        todayOnlineMinutes: 180,
        todayEarnings: 320.00,
        avgSessionRating: 4.7,
        customTimeEnabled: false,
        customPriceEnabled: true,
        sessionConfigs: [
          SessionConfig(
            id: 'sc3',
            name: '45min Legal Consultation',
            durationMinutes: 45,
            price: 80.0,
          ),
        ],
        verificationStatus: VerificationStatus.verified,
        workExperience: 'LLB from Cairo University, 12 years in corporate law, specializing in international business transactions.',
        qualifications: 'Licensed attorney in Egypt and UAE, Member of International Bar Association',
        country: 'Egypt',
        verificationAttachments: [
          {
            'type': 'Document',
            'title': 'Law Degree',
            'description': 'LLB from Cairo University',
            'url': 'law_degree.pdf'
          },
          {
            'type': 'Document',
            'title': 'Bar License UAE',
            'description': 'Licensed attorney in UAE',
            'url': 'bar_license_uae.pdf'
          },
          {
            'type': 'Link',
            'title': 'LinkedIn Profile',
            'description': 'Professional LinkedIn profile',
            'url': 'https://linkedin.com/in/ahmed-alrashid'
          }
        ],
      ),
      Expert(
        id: 'exp3',
        name: 'Maria Garcia',
        nameArabic: 'ماريا غارسيا',
        email: 'maria.g@chatpro.com',
        profileImage: "https://pixabay.com/get/g94ee15922fe0b99ead203605a76c811d44b50875aa5c0d875203078cab8f45c7afe55e1386b1a6018fdbf637af0b3c0ee4b7076bb1b3abd3d5eee863feae9c56_1280.jpg",
        bio: 'Licensed clinical psychologist specializing in anxiety, depression, and relationship counseling. Offering compassionate support.',
        category: ExpertCategory.therapist,
        subcategories: ['Cognitive Behavioral Therapy', 'Trauma Therapy'],
        subcategoriesArabic: ['العلاج المعرفي السلوكي', 'علاج الصدمات'],
        languages: ['English'],
        rating: 4.9,
        totalReviews: 267,
        pricePerMinute: 3.00,
        pricePerSession: 120.00,
        isAvailable: true,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 280)),
        regions: ['All'],
        todaySessionCount: 6,
        todayOnlineMinutes: 200,
        todayEarnings: 280.00,
        avgSessionRating: 4.9,
        verificationStatus: VerificationStatus.verified,
        workExperience: 'PhD in Clinical Psychology from Stanford, 8 years in private practice, specializing in trauma therapy.',
        qualifications: 'Licensed Clinical Psychologist, Certified in EMDR and CBT',
        country: 'United States',
        verificationAttachments: [
          {
            'type': 'Document',
            'title': 'Psychology License',
            'description': 'Licensed Clinical Psychologist certification',
            'url': 'psychology_license.pdf'
          },
          {
            'type': 'Document',
            'title': 'Stanford PhD Diploma',
            'description': 'PhD in Clinical Psychology from Stanford',
            'url': 'stanford_phd.pdf'
          },
          {
            'type': 'Document',
            'title': 'EMDR Certification',
            'description': 'Certified in EMDR therapy',
            'url': 'emdr_cert.pdf'
          }
        ],
      ),
      Expert(
        id: 'exp4',
        name: 'David Chen',
        email: 'david.c@chatpro.com',
        profileImage: "https://pixabay.com/get/g22b7d7b09b60d8475e72da76399ef720c967f871e4c9b776a5183ac3ae483ef458124989e07b4069987870d0e7ff18aa5ddfe36f87a50196abb94da37cd4d2a4_1280.jpg",
        bio: 'Business strategy consultant with MBA from Harvard. Helping startups and SMEs scale their operations and improve profitability.',
        category: ExpertCategory.businessConsultant,
        subcategories: ['Strategic Planning', 'Startup Consulting'],
        languages: ['English'],
        rating: 4.7,
        totalReviews: 156,
        pricePerMinute: 3.50,
        pricePerSession: 200.00,
        isAvailable: true,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 180)),
        regions: ['All'],
        todaySessionCount: 4,
        todayOnlineMinutes: 160,
        todayEarnings: 350.00,
        avgSessionRating: 4.8,
        verificationStatus: VerificationStatus.underReview,
        workExperience: 'MBA from Harvard Business School, 10 years in management consulting at McKinsey & Company.',
        qualifications: 'CPA, Six Sigma Black Belt, Former McKinsey Senior Partner',
        country: 'United States',
        verificationAttachments: [
          {
            'type': 'Document',
            'title': 'Harvard MBA Diploma',
            'description': 'MBA from Harvard Business School',
            'url': 'harvard_mba.pdf'
          },
          {
            'type': 'Document',
            'title': 'CPA Certificate',
            'description': 'Certified Public Accountant license',
            'url': 'cpa_certificate.pdf'
          },
          {
            'type': 'Document',
            'title': 'Six Sigma Black Belt',
            'description': 'Six Sigma Black Belt certification',
            'url': 'six_sigma_cert.pdf'
          },
          {
            'type': 'Link',
            'title': 'McKinsey Profile',
            'description': 'Former McKinsey Senior Partner profile',
            'url': 'https://mckinsey.com/our-people/david-chen'
          }
        ],
      ),
      Expert(
        id: 'exp5',
        name: 'Fatima Al-Zahra',
        email: 'fatima.z@chatpro.com',
        profileImage: "https://pixabay.com/get/g5e0546044477a75c5cee534b90336596cc1d420c76bbfbfc8ae622c1b778b56b13f3a1961f13e9199c18819b3783fe619d64f7286cce5edf45d00bda9d884018_1280.jpg",
        bio: 'Certified life coach and motivational speaker. Helping individuals achieve personal growth and career success through structured guidance.',
        category: ExpertCategory.lifeCoach,
        subcategories: ['Personal Development', 'Career Coaching'],
        languages: ['Arabic', 'English'],
        rating: 4.8,
        totalReviews: 234,
        pricePerMinute: 2.00,
        pricePerSession: 80.00,
        isAvailable: true,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 365)),
        regions: ['All'],
        todaySessionCount: 7,
        todayOnlineMinutes: 220,
        todayEarnings: 280.00,
        avgSessionRating: 4.8,
        verificationStatus: VerificationStatus.verified,
        workExperience: 'Certified Life Coach with 5 years of experience, specializing in personal development and career coaching.',
        qualifications: 'ICF Certified Life Coach, NLP Practitioner, Motivational Speaker',
        country: 'UAE',
        verificationAttachments: [
          {
            'type': 'Document',
            'title': 'ICF Certification',
            'description': 'International Coach Federation certification',
            'url': 'icf_cert.pdf'
          },
          {
            'type': 'Document',
            'title': 'NLP Practitioner Certificate',
            'description': 'Neuro-Linguistic Programming certification',
            'url': 'nlp_cert.pdf'
          }
        ],
      ),
      Expert(
        id: 'exp6',
        name: 'Omar Hassan',
        email: 'omar.h@chatpro.com',
        profileImage: "https://pixabay.com/get/g91bf7d271d9bf0d899efdefed903f76419ada1bd21bcfb3d15431ee568582e73aa03184c504b87eb88685c4fa72fa0adc054005e04a9ae5710539390b346b238_1280.jpg",
        bio: 'Senior software engineer and technical consultant. Specializing in mobile app development, cloud architecture, and system optimization.',
        category: ExpertCategory.technician,
        subcategories: ['Mobile App Development', 'Cloud Computing'],
        languages: ['Arabic', 'English'],
        rating: 4.6,
        totalReviews: 89,
        pricePerMinute: 2.75,
        pricePerSession: 100.00,
        isAvailable: false,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 120)),
        regions: ['All'],
        todaySessionCount: 3,
        todayOnlineMinutes: 140,
        todayEarnings: 195.50,
        avgSessionRating: 4.5,
        verificationStatus: VerificationStatus.verified,
        workExperience: 'Senior Software Engineer with 8 years in mobile development and cloud architecture.',
        qualifications: 'BS Computer Science, AWS Certified Solutions Architect, Google Cloud Professional',
        country: 'Jordan',
        verificationAttachments: [
          {
            'type': 'Document',
            'title': 'Computer Science Degree',
            'description': 'BS in Computer Science',
            'url': 'cs_degree.pdf'
          },
          {
            'type': 'Document',
            'title': 'AWS Certification',
            'description': 'AWS Certified Solutions Architect',
            'url': 'aws_cert.pdf'
          },
          {
            'type': 'Link',
            'title': 'GitHub Portfolio',
            'description': 'Professional GitHub profile with projects',
            'url': 'https://github.com/omarhassan'
          }
        ],
      ),
      // Business Expert: Healthcare Team
      Expert(
        id: 'exp7',
        name: 'HealthCare Plus Clinic',
        nameArabic: 'عيادة هيلث كير بلاس',
        email: 'info@healthcareplus.com',
        profileImage: "https://pixabay.com/get/g5e0546044477a75c5cee534b90336596cc1d420c76bbfbfc8ae622c1b778b56b13f3a1961f13e9199c18819b3783fe619d64f7286cce5edf45d00bda9d884018_1280.jpg",
        bio: 'Professional healthcare team with specialists in family medicine, pediatrics, and cardiology. Offering comprehensive medical consultations.',
        category: ExpertCategory.doctor,
        subcategories: ['General Medicine', 'Pediatrics', 'Cardiology'],
        subcategoriesArabic: ['الطب العام', 'طب الأطفال', 'أمراض القلب'],
        languages: ['English', 'Arabic'],
        rating: 4.8,
        totalReviews: 156,
        pricePerMinute: 3.00,
        pricePerSession: 100.00,
        isAvailable: true,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 200)),
        regions: ['All'],
        todaySessionCount: 12,
        todayOnlineMinutes: 360,
        todayEarnings: 650.00,
        avgSessionRating: 4.8,
        isBusinessExpert: true,
        teamName: 'HealthCare Plus Medical Team',
        teamDescription: 'Our team consists of experienced doctors specializing in various medical fields to provide comprehensive healthcare services.',
        teamMemberIds: ['exp8', 'exp9', 'exp10'],
        verificationAttachments: [],
      ),
      // Team Member 1
      Expert(
        id: 'exp8',
        name: 'Dr. John Smith',
        email: 'john.smith@healthcareplus.com',
        profileImage: "https://pixabay.com/get/gb463c8ac24ee253fb2afa8443273cef0454bafc517908164c95cbfdaef4b204bbcfabb158972f55d174879c0acaad0547d55bf66fff96303b7db8cea62efcbf8_1280.jpg",
        bio: 'Cardiologist with 12 years of experience. Specializes in heart disease prevention and treatment.',
        category: ExpertCategory.doctor,
        subcategories: ['Cardiology'],
        languages: ['English'],
        rating: 4.9,
        totalReviews: 87,
        pricePerMinute: 3.50,
        pricePerSession: 120.00,
        isAvailable: true,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 180)),
        regions: ['UAE', 'UK'],
        todaySessionCount: 4,
        todayOnlineMinutes: 160,
        todayEarnings: 280.00,
        avgSessionRating: 4.9,
        parentBusinessId: 'exp7',
        verificationAttachments: [],
      ),
      // Team Member 2
      Expert(
        id: 'exp9',
        name: 'Dr. Lisa Wang',
        email: 'lisa.wang@healthcareplus.com',
        profileImage: "https://pixabay.com/get/g94ee15922fe0b99ead203605a76c811d44b50875aa5c0d875203078cab8f45c7afe55e1386b1a6018fdbf637af0b3c0ee4b7076bb1b3abd3d5eee863feae9c56_1280.jpg",
        bio: 'Pediatrician specializing in child health and development. Experienced in treating infants, children, and adolescents.',
        category: ExpertCategory.doctor,
        subcategories: ['Pediatrics'],
        languages: ['English', 'Arabic'],
        rating: 4.8,
        totalReviews: 63,
        pricePerMinute: 3.00,
        pricePerSession: 110.00,
        isAvailable: true,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 150)),
        regions: ['UAE'],
        todaySessionCount: 3,
        todayOnlineMinutes: 120,
        todayEarnings: 210.00,
        avgSessionRating: 4.8,
        parentBusinessId: 'exp7',
        verificationAttachments: [],
      ),
      // Team Member 3
      Expert(
        id: 'exp10',
        name: 'Dr. Michael Brown',
        email: 'michael.brown@healthcareplus.com',
        profileImage: "https://pixabay.com/get/g22b7d7b09b60d8475e72da76399ef720c967f871e4c9b776a5183ac3ae483ef458124989e07b4069987870d0e7ff18aa5ddfe36f87a50196abb94da37cd4d2a4_1280.jpg",
        bio: 'Family medicine physician with expertise in preventive care and chronic disease management.',
        category: ExpertCategory.doctor,
        subcategories: ['General Medicine'],
        languages: ['English'],
        rating: 4.7,
        totalReviews: 45,
        pricePerMinute: 2.80,
        pricePerSession: 95.00,
        isAvailable: false,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 120)),
        regions: ['UK'],
        todaySessionCount: 2,
        todayOnlineMinutes: 80,
        todayEarnings: 160.00,
        avgSessionRating: 4.7,
        parentBusinessId: 'exp7',
        verificationAttachments: [],
      ),
      // Business Expert: Legal Associates
      Expert(
        id: 'exp11',
        name: 'Al-Rashid Legal Associates',
        nameArabic: 'شركاء الراشد القانونية',
        email: 'info@alrashidlegal.com',
        profileImage: "https://pixabay.com/get/g91005b1ef8d8657afde26a0fb46b9db7a67708f62bbbe3d142c764b1e30725c6f8bd301a2525ff6dae36e3175dc9b8666e57d8bda2323f561e86500342a6ea70_1280.jpg",
        bio: 'Leading legal firm specializing in corporate law, real estate, and litigation. Our team of experienced lawyers provides comprehensive legal services.',
        category: ExpertCategory.lawyer,
        subcategories: ['Corporate Law', 'Real Estate Law'],
        subcategoriesArabic: ['القانون التجاري', 'قانون العقار'],
        languages: ['Arabic', 'English'],
        rating: 4.9,
        totalReviews: 203,
        pricePerMinute: 4.50,
        pricePerSession: 180.00,
        isAvailable: true,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 300)),
        regions: ['UAE'],
        todaySessionCount: 8,
        todayOnlineMinutes: 320,
        todayEarnings: 720.00,
        avgSessionRating: 4.9,
        isBusinessExpert: true,
        teamName: 'Al-Rashid Legal Team',
        teamDescription: 'Our legal team consists of specialized lawyers with expertise in various areas of law to serve all your legal needs.',
        teamMemberIds: ['exp12', 'exp13'],
        verificationAttachments: [],
      ),
      // Team Member 4
      Expert(
        id: 'exp12',
        name: 'Saeed Al-Rashid',
        email: 'saeed@alrashidlegal.com',
        profileImage: "https://pixabay.com/get/g91005b1ef8d8657afde26a0fb46b9db7a67708f62bbbe3d142c764b1e30725c6f8bd301a2525ff6dae36e3175dc9b8666e57d8bda2323f561e86500342a6ea70_1280.jpg",
        bio: 'Senior partner specializing in corporate law and business transactions. Over 20 years of experience.',
        category: ExpertCategory.lawyer,
        subcategories: ['Corporate Law'],
        languages: ['Arabic', 'English'],
        rating: 4.9,
        totalReviews: 145,
        pricePerMinute: 5.00,
        pricePerSession: 200.00,
        isAvailable: true,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 280)),
        regions: ['UAE'],
        todaySessionCount: 5,
        todayOnlineMinutes: 200,
        todayEarnings: 400.00,
        avgSessionRating: 4.9,
        parentBusinessId: 'exp11',
        verificationAttachments: [],
      ),
      // Team Member 5
      Expert(
        id: 'exp13',
        name: 'Nora Al-Mansouri',
        email: 'nora@alrashidlegal.com',
        profileImage: "https://pixabay.com/get/g5e0546044477a75c5cee534b90336596cc1d420c76bbfbfc8ae622c1b778b56b13f3a1961f13e9199c18819b3783fe619d64f7286cce5edf45d00bda9d884018_1280.jpg",
        bio: 'Real estate and property law specialist. Experienced in commercial and residential property transactions.',
        category: ExpertCategory.lawyer,
        subcategories: ['Real Estate Law'],
        languages: ['Arabic', 'English'],
        rating: 4.8,
        totalReviews: 76,
        pricePerMinute: 4.20,
        pricePerSession: 170.00,
        isAvailable: true,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 200)),
        regions: ['UAE'],
        todaySessionCount: 3,
        todayOnlineMinutes: 150,
        todayEarnings: 320.00,
        avgSessionRating: 4.8,
        parentBusinessId: 'exp11',
        verificationAttachments: [],
      ),
      // Business Expert: TechConsult Solutions
      Expert(
        id: 'exp14',
        name: 'TechConsult Solutions',
        nameArabic: 'حلول تك كونسلت',
        email: 'info@techconsult.com',
        profileImage: "https://pixabay.com/get/g8e1d44cdc30ab4c1eabdee6ef5adc8f4f926d64b9c51a24b4f5d09324ba3b8b3aea94b0d2eb0a5fdbc9a8e4f1b0fcaae04fd2edc734d5af64ea3aeb7ec55a9a93_1280.jpg",
        bio: 'Leading technology consulting firm specializing in digital transformation, software development, and IT strategy. Our expert team helps businesses navigate the digital landscape.',
        category: ExpertCategory.technician,
        subcategories: ['Software Development', 'IT Consulting'],
        subcategoriesArabic: ['تطوير البرمجيات', 'استشارات تقنية'],
        languages: ['English', 'Arabic'],
        rating: 4.8,
        totalReviews: 156,
        pricePerMinute: 3.50,
        pricePerSession: 120.00,
        isAvailable: true,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 400)),
        regions: ['UAE', 'US'],
        todaySessionCount: 6,
        todayOnlineMinutes: 280,
        todayEarnings: 640.00,
        avgSessionRating: 4.8,
        isBusinessExpert: true,
        teamName: 'TechConsult Expert Team',
        teamDescription: 'Our technology team consists of senior developers, system architects, and IT consultants with years of experience in various technologies.',
        teamMemberIds: ['exp15', 'exp16'],
        verificationAttachments: [],
      ),
      // Team Member 6
      Expert(
        id: 'exp15',
        name: 'David Kumar',
        email: 'david@techconsult.com',
        profileImage: "https://pixabay.com/get/g8e1d44cdc30ab4c1eabdee6ef5adc8f4f926d64b9c51a24b4f5d09324ba3b8b3aea94b0d2eb0a5fdbc9a8e4f1b0fcaae04fd2edc734d5af64ea3aeb7ec55a9a93_1280.jpg",
        bio: 'Senior Software Architect with expertise in cloud computing, microservices, and enterprise application development.',
        category: ExpertCategory.technician,
        subcategories: ['Cloud Computing', 'Software Development'],
        languages: ['English'],
        rating: 4.9,
        totalReviews: 89,
        pricePerMinute: 4.00,
        pricePerSession: 140.00,
        isAvailable: true,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 350)),
        regions: ['US'],
        todaySessionCount: 4,
        todayOnlineMinutes: 200,
        todayEarnings: 400.00,
        avgSessionRating: 4.9,
        parentBusinessId: 'exp14',
        verificationAttachments: [],
      ),
      // Team Member 7
      Expert(
        id: 'exp16',
        name: 'Sarah Ahmed',
        email: 'sarah@techconsult.com',
        profileImage: "https://pixabay.com/get/g5e0546044477a75c5cee534b90336596cc1d420c76bbfbfc8ae622c1b778b56b13f3a1961f13e9199c18819b3783fe619d64f7286cce5edf45d00bda9d884018_1280.jpg",
        bio: 'DevOps Engineer and cybersecurity specialist focusing on secure cloud infrastructure and automation.',
        category: ExpertCategory.technician,
        subcategories: ['DevOps', 'Cybersecurity'],
        languages: ['English', 'Arabic'],
        rating: 4.7,
        totalReviews: 67,
        pricePerMinute: 3.80,
        pricePerSession: 130.00,
        isAvailable: false,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 250)),
        regions: ['UAE'],
        todaySessionCount: 3,
        todayOnlineMinutes: 150,
        todayEarnings: 285.00,
        avgSessionRating: 4.7,
        parentBusinessId: 'exp14',
        verificationAttachments: [],
      ),
      // Business Expert: Wellness & Therapy Center
      Expert(
        id: 'exp17',
        name: 'Wellness & Therapy Center',
        nameArabic: 'مركز العافية والعلاج',
        email: 'info@wellnesscenter.com',
        profileImage: "https://pixabay.com/get/g5e0546044477a75c5cee534b90336596cc1d420c76bbfbfc8ae622c1b778b56b13f3a1961f13e9199c18819b3783fe619d64f7286cce5edf45d00bda9d884018_1280.jpg",
        bio: 'Comprehensive mental health and wellness center offering therapy, counseling, and life coaching services. Our team of licensed professionals provides personalized care.',
        category: ExpertCategory.therapist,
        subcategories: ['Marriage Counseling', 'Trauma Therapy'],
        subcategoriesArabic: ['استشارات زوجية', 'علاج الصدمات'],
        languages: ['English', 'Arabic'],
        rating: 4.9,
        totalReviews: 278,
        pricePerMinute: 3.00,
        pricePerSession: 100.00,
        isAvailable: true,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 500)),
        regions: ['UAE', 'UK'],
        todaySessionCount: 12,
        todayOnlineMinutes: 400,
        todayEarnings: 850.00,
        avgSessionRating: 4.9,
        isBusinessExpert: true,
        teamName: 'Wellness Professional Team',
        teamDescription: 'Our multidisciplinary team includes licensed therapists, psychologists, and life coaches dedicated to supporting your mental health and personal growth.',
        teamMemberIds: ['exp18', 'exp19'],
        verificationAttachments: [],
      ),
      // Team Member 8
      Expert(
        id: 'exp18',
        name: 'Dr. Amanda Foster',
        email: 'amanda@wellnesscenter.com',
        profileImage: "https://pixabay.com/get/g5e0546044477a75c5cee534b90336596cc1d420c76bbfbfc8ae622c1b778b56b13f3a1961f13e9199c18819b3783fe619d64f7286cce5edf45d00bda9d884018_1280.jpg",
        bio: 'Licensed Clinical Psychologist specializing in anxiety, depression, and relationship counseling. PhD in Clinical Psychology.',
        category: ExpertCategory.therapist,
        subcategories: ['Cognitive Behavioral Therapy', 'Behavioral Therapy'],
        languages: ['English'],
        rating: 4.9,
        totalReviews: 134,
        pricePerMinute: 3.50,
        pricePerSession: 120.00,
        isAvailable: true,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 450)),
        regions: ['UK'],
        todaySessionCount: 6,
        todayOnlineMinutes: 240,
        todayEarnings: 480.00,
        avgSessionRating: 4.9,
        parentBusinessId: 'exp17',
        verificationAttachments: [],
      ),
      // Team Member 9
      Expert(
        id: 'exp19',
        name: 'Omar Al-Zahra',
        email: 'omar@wellnesscenter.com',
        profileImage: "https://pixabay.com/get/g91005b1ef8d8657afde26a0fb46b9db7a67708f62bbbe3d142c764b1e30725c6f8bd301a2525ff6dae36e3175dc9b8666e57d8bda2323f561e86500342a6ea70_1280.jpg",
        bio: 'Licensed Marriage and Family Therapist with expertise in couples counseling and family dynamics. Bilingual therapy services.',
        category: ExpertCategory.therapist,
        subcategories: ['Marriage Counseling', 'Family Therapy'],
        languages: ['Arabic', 'English'],
        rating: 4.8,
        totalReviews: 92,
        pricePerMinute: 3.20,
        pricePerSession: 110.00,
        isAvailable: true,
        isVerified: true,
        joinedAt: DateTime.now().subtract(const Duration(days: 380)),
        regions: ['UAE'],
        todaySessionCount: 4,
        todayOnlineMinutes: 180,
        todayEarnings: 360.00,
        avgSessionRating: 4.8,
        parentBusinessId: 'exp17',
        verificationStatus: VerificationStatus.verified,
        workExperience: 'Licensed Marriage and Family Therapist with 8 years of experience in couples counseling.',
        qualifications: 'LMFT, Gottman Method Couples Therapy certified',
        country: 'UAE',
        verificationAttachments: [],
      ),
      // Test expert with underReview status
      Expert(
        id: 'exp20',
        name: 'Dr. James Wilson',
        email: 'james.w@chatpro.com',
        profileImage: "https://pixabay.com/get/g91bf7d271d9bf0d899efdefed903f76419ada1bd21bcfb3d15431ee568582e73aa03184c504b87eb88685c4fa72fa0adc054005e04a9ae5710539390b346b238_1280.jpg",
        bio: 'Board-certified psychiatrist specializing in anxiety disorders and depression treatment.',
        category: ExpertCategory.doctor,
        subcategories: ['Psychiatry', 'Mental Health'],
        languages: ['English'],
        rating: 0.0,
        totalReviews: 0,
        pricePerMinute: 3.00,
        pricePerSession: 120.00,
        isAvailable: false,
        isVerified: false,
        joinedAt: DateTime.now().subtract(const Duration(days: 5)),
        regions: ['All'],
        todaySessionCount: 0,
        todayOnlineMinutes: 0,
        todayEarnings: 0.0,
        avgSessionRating: 0.0,
        verificationStatus: VerificationStatus.underReview,
        workExperience: 'MD from Johns Hopkins, 12 years in psychiatry, residency at Massachusetts General Hospital.',
        qualifications: 'Board-certified psychiatrist, Member of American Psychiatric Association',
        country: 'United States',
        verificationAttachments: [
          {
            'type': 'Document',
            'title': 'Medical License',
            'description': 'Board certification in Psychiatry',
            'url': 'psychiatry_license.pdf'
          },
          {
            'type': 'Document',
            'title': 'Johns Hopkins MD',
            'description': 'Medical degree from Johns Hopkins University',
            'url': 'johns_hopkins_md.pdf'
          },
          {
            'type': 'Document',
            'title': 'Mass General Residency',
            'description': 'Psychiatry residency certificate',
            'url': 'mass_general_residency.pdf'
          },
          {
            'type': 'Document',
            'title': 'APA Membership',
            'description': 'American Psychiatric Association membership',
            'url': 'apa_membership.pdf'
          },
          {
            'type': 'Image',
            'title': 'Professional ID Photo',
            'description': 'Professional identification photo',
            'url': 'professional_id.jpg'
          }
        ],
      ),
    ];
  }

  static List<ConsultationSession> getSessionHistory() {
    return [
      ConsultationSession(
        id: 'session1',
        clientId: 'client1',
        expertId: 'exp1',
        type: SessionType.video,
        status: SessionStatus.ended,
        startTime: DateTime.now().subtract(const Duration(days: 2)),
        endTime: DateTime.now().subtract(const Duration(days: 2, hours: -1)),
        totalCost: 150.00,
        durationMinutes: 60,
        rating: 5.0,
        review: 'Excellent consultation! Dr. Johnson was very professional and helpful.',
        isPaidPerMinute: false,
      ),
      ConsultationSession(
        id: 'session2',
        clientId: 'client1',
        expertId: 'exp2',
        type: SessionType.chat,
        status: SessionStatus.ended,
        startTime: DateTime.now().subtract(const Duration(days: 5)),
        endTime: DateTime.now().subtract(const Duration(days: 5, hours: -0, minutes: -30)),
        totalCost: 120.00,
        durationMinutes: 30,
        rating: 4.5,
        review: 'Good legal advice, very knowledgeable.',
        isPaidPerMinute: true,
      ),
      ConsultationSession(
        id: 'session3',
        clientId: 'client1',
        expertId: 'exp3',
        type: SessionType.voice,
        status: SessionStatus.ended,
        startTime: DateTime.now().subtract(const Duration(days: 7)),
        endTime: DateTime.now().subtract(const Duration(days: 7, hours: -0, minutes: -45)),
        totalCost: 135.00,
        durationMinutes: 45,
        rating: 5.0,
        review: 'Maria was incredibly understanding and provided great insights.',
        isPaidPerMinute: true,
      ),
    ];
  }

  static List<ChatMessage> getChatMessages(String sessionId) {
    return [
      ChatMessage(
        id: 'msg1',
        senderId: 'client1',
        receiverId: 'exp1',
        content: 'Hello Dr. Johnson, I have some questions about my recent symptoms.',
        type: MessageType.text,
        timestamp: DateTime.now().subtract(const Duration(minutes: 30)),
        isRead: true,
      ),
      ChatMessage(
        id: 'msg2',
        senderId: 'exp1',
        receiverId: 'client1',
        content: 'Hello! I\'m here to help. Please describe your symptoms in detail.',
        type: MessageType.text,
        timestamp: DateTime.now().subtract(const Duration(minutes: 29)),
        isRead: true,
      ),
      ChatMessage(
        id: 'msg3',
        senderId: 'client1',
        receiverId: 'exp1',
        content: 'I\'ve been experiencing headaches and fatigue for the past week.',
        type: MessageType.text,
        timestamp: DateTime.now().subtract(const Duration(minutes: 28)),
        isRead: true,
      ),
      ChatMessage(
        id: 'msg4',
        senderId: 'exp1',
        receiverId: 'client1',
        content: 'I understand your concern. How would you rate the intensity of your headaches on a scale of 1-10?',
        type: MessageType.text,
        timestamp: DateTime.now().subtract(const Duration(minutes: 27)),
        isRead: true,
      ),
      ChatMessage(
        id: 'msg5',
        senderId: 'client1',
        receiverId: 'exp1',
        content: 'I\'d say around 6-7. They\'re quite persistent.',
        type: MessageType.text,
        timestamp: DateTime.now().subtract(const Duration(minutes: 26)),
        isRead: true,
      ),
      ChatMessage(
        id: 'msg6',
        senderId: 'exp1',
        receiverId: 'client1',
        content: 'Let me ask you a few more questions to better understand your condition. Are you experiencing any vision changes?',
        type: MessageType.text,
        timestamp: DateTime.now().subtract(const Duration(minutes: 25)),
        isRead: false,
      ),
    ];
  }

  static List<Appointment> getAppointments() {
    return [
      // UAE Region appointments
      Appointment(
        id: 'apt1',
        clientId: 'client1',
        expertId: 'exp1', // Dr. Sarah Johnson (UAE, UK)
        scheduledTime: DateTime.now().add(const Duration(days: 1, hours: 10)),
        durationMinutes: 60,
        totalCost: 75.00,
        title: 'General Health Consultation',
        description: 'Routine checkup and health assessment',
        status: AppointmentStatus.scheduled,
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
        paymentType: PaymentType.perSession,
        clientName: 'John Doe',
        expertName: 'Dr. Sarah Johnson',
      ),
      Appointment(
        id: 'apt2',
        clientId: 'client1',
        expertId: 'exp2', // Ahmed Al-Rashid (UAE only)
        scheduledTime: DateTime.now().add(const Duration(days: 3, hours: 14)),
        durationMinutes: 90,
        totalCost: 150.00,
        title: 'Legal Contract Review',
        description: 'Review of employment contract terms',
        status: AppointmentStatus.scheduled,
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        paymentType: PaymentType.perSession,
        clientName: 'John Doe',
        expertName: 'Ahmed Al-Rashid',
      ),
      Appointment(
        id: 'apt3',
        clientId: 'client2',
        expertId: 'exp5', // Fatima Al-Zahra (UAE only)
        scheduledTime: DateTime.now().add(const Duration(days: 2, hours: 9)),
        durationMinutes: 60,
        totalCost: 90.00,
        title: 'Career Coaching Session',
        description: 'Guidance on career transition and growth opportunities',
        status: AppointmentStatus.scheduled,
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        paymentType: PaymentType.perSession,
        clientName: 'Sarah Ahmed',
        expertName: 'Fatima Al-Zahra',
      ),
      Appointment(
        id: 'apt4',
        clientId: 'client2',
        expertId: 'exp6', // Dr. Robert Smith (UAE, UK)
        scheduledTime: DateTime.now().add(const Duration(days: 4, hours: 16)),
        durationMinutes: 45,
        totalCost: 67.50,
        title: 'Home Electrical Inspection',
        description: 'Safety inspection and electrical system maintenance',
        status: AppointmentStatus.scheduled,
        createdAt: DateTime.now().subtract(const Duration(hours: 5)),
        paymentType: PaymentType.perSession,
        clientName: 'Sarah Ahmed',
        expertName: 'Dr. Robert Smith',
      ),
      // UK Region appointments (won't be visible to UAE clients)
      Appointment(
        id: 'apt5',
        clientId: 'client3',
        expertId: 'exp3', // Maria Garcia (UK only)
        scheduledTime: DateTime.now().add(const Duration(days: 1, hours: 15)),
        durationMinutes: 60,
        totalCost: 120.00,
        title: 'Therapy Session',
        description: 'Anxiety and stress management counseling',
        status: AppointmentStatus.scheduled,
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        paymentType: PaymentType.perSession,
        clientName: 'Emma Wilson',
        expertName: 'Maria Garcia',
      ),
      Appointment(
        id: 'apt6',
        clientId: 'client3',
        expertId: 'exp4', // David Chen (UK only)
        scheduledTime: DateTime.now().add(const Duration(days: 5, hours: 11)),
        durationMinutes: 120,
        totalCost: 200.00,
        title: 'Business Strategy Review',
        description: 'Quarterly business performance analysis and planning',
        status: AppointmentStatus.scheduled,
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
        paymentType: PaymentType.perSession,
        clientName: 'Emma Wilson',
        expertName: 'David Chen',
      ),
      // Some cancelled appointments for demonstration
      Appointment(
        id: 'apt7',
        clientId: 'client1',
        expertId: 'exp1',
        scheduledTime: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
        durationMinutes: 30,
        totalCost: 37.50,
        title: 'Quick Health Check',
        description: 'Brief consultation for minor health concerns',
        status: AppointmentStatus.cancelled,
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
        paymentType: PaymentType.perSession,
        clientName: 'John Doe',
        expertName: 'Dr. Sarah Johnson',
      ),
      Appointment(
        id: 'apt8',
        clientId: 'client2',
        expertId: 'exp2',
        scheduledTime: DateTime.now().subtract(const Duration(days: 2, hours: 3)),
        durationMinutes: 60,
        totalCost: 150.00,
        title: 'Legal Consultation',
        description: 'Property law advice and documentation',
        status: AppointmentStatus.completed,
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        paymentType: PaymentType.perSession,
        clientName: 'Sarah Ahmed',
        expertName: 'Ahmed Al-Rashid',
      ),
    ];
  }

  static Map<String, String> getTranslations() {
    return {
      // English
      'en_app_title': 'ExpertChat',
      'en_welcome': 'Welcome to ExpertChat',
      'en_find_expert': 'Find Expert',
      'en_categories': 'Categories',
      'en_search_hint': 'Search for experts...',
      'en_doctors': 'Doctors',
      'en_lawyers': 'Lawyers',
      'en_therapists': 'Therapists',
      'en_life_coaches': 'Life Coaches',
      'en_business_consultants': 'Business Consultants',
      'en_technicians': 'Technicians',
      'en_religion': 'Religion',
      'en_available': 'Available',
      'en_offline': 'Offline',
      'en_per_minute': 'per minute',
      'en_per_session': 'per session',
      'en_start_chat': 'Start Chat',
      'en_voice_call': 'Voice Call',
      'en_video_call': 'Video Call',
      'en_rating': 'Rating',
      'en_reviews': 'Reviews',
      'en_verified': 'Verified',
      'en_session_history': 'Session History',
      'en_settings': 'Settings',
      'en_profile': 'Profile',
      'en_dark_mode': 'Dark Mode',
      'en_language': 'Language',
      'en_logout': 'Logout',
      'en_login': 'Login',
      'en_sign_in': 'Sign In/Up',
      'en_signup': 'Sign Up',
      'en_expert_signup': 'Expert Sign Up',
      'en_email': 'Email',
      'en_password': 'Password',
      'en_name': 'Name',
      'en_join_as_expert': 'Expert',
      'en_join_as_expert_signup': 'Join as Expert',
      'en_already_have_account': 'Already have an account?',
      'en_dont_have_account': 'Don\'t have an account?',
      'en_today_sessions': 'Today\'s Sessions',
      'en_online_time': 'Online Time',
      'en_earnings': 'Earnings',
      'en_avg_rating': 'Average Rating',
      'en_dashboard': 'Dashboard',
      'en_type_message': 'Type a message...',
      'en_session_timer': 'Session Timer',
      'en_total_cost': 'Total Cost',
      'en_end_session': 'End Session',
      'en_session_ended': 'Session Ended',
      'en_rate_expert': 'Rate Expert',
      'en_add_comment': 'Add Comment (Optional)',
      'en_share_experience': 'Share your experience with this expert...',
      'en_skip': 'Skip',
      'en_submit_review': 'Submit Review',
      'en_review_submitted': 'Thank you for your review!',
      'en_review_error': 'Failed to submit review. Please try again.',
      'en_duration': 'Duration',
      'en_write_review': 'Write Review',
      'en_submit_review': 'Submit Review',
      'en_payment_method': 'Payment Method',
      'en_pay_per_minute': 'Pay Per Minute',
      'en_pay_per_session': 'Pay Per Session',
      'en_start_session': 'Start Session',
      'en_minutes': 'minutes',
      'en_hours': 'hours',
      'en_home': 'Home',
      'en_recent_chats': 'Recent Chats',
      'en_view_all': 'View All',
      'en_available_experts': 'Available Experts',
      'en_clear_filters': 'Clear Filters',
      'en_no_experts_found': 'No experts found',
      'en_days_ago': '{days} days ago',
      'en_hours_ago': '{hours} hours ago',
      'en_minutes_ago': '{minutes} minutes ago',
      'en_just_now': 'Just now',
      'en_subcategories': 'Subcategories',
      'en_select_subcategory': 'Select a subcategory',
      'en_show_all': 'Show All',
      
      // Arabic
      'ar_app_title': 'إكسبرت شات',
      'ar_welcome': 'مرحباً بك في إكسبرت شات',
      'ar_find_expert': 'العثور على خبير',
      'ar_categories': 'الفئات',
      'ar_search_hint': 'البحث عن خبراء...',
      'ar_doctors': 'الأطباء',
      'ar_lawyers': 'المحامون',
      'ar_therapists': 'المعالجون النفسيون',
      'ar_life_coaches': 'مدربو الحياة',
      'ar_business_consultants': 'الاستشاريون التجاريون',
      'ar_technicians': 'التقنيون',
      'ar_religion': 'الدين',
      'ar_available': 'متاح',
      'ar_offline': 'غير متصل',
      'ar_per_minute': 'في الدقيقة',
      'ar_per_session': 'في الجلسة',
      'ar_start_chat': 'بدء المحادثة',
      'ar_voice_call': 'مكالمة صوتية',
      'ar_video_call': 'مكالمة فيديو',
      'ar_rating': 'التقييم',
      'ar_reviews': 'المراجعات',
      'ar_verified': 'موثق',
      'ar_session_history': 'سجل الجلسات',
      'ar_settings': 'الإعدادات',
      'ar_profile': 'الملف الشخصي',
      'ar_dark_mode': 'الوضع المظلم',
      'ar_language': 'اللغة',
      'ar_logout': 'تسجيل الخروج',
      'ar_login': 'تسجيل الدخول',
      'ar_sign_in': 'تسجيل الدخول',
      'ar_signup': 'إنشاء حساب',
      'ar_expert_signup': 'تسجيل خبير',
      'ar_email': 'البريد الإلكتروني',
      'ar_password': 'كلمة المرور',
      'ar_name': 'الاسم',
      'ar_join_as_expert': 'خبير',
      'ar_join_as_expert_signup': 'انضم كخبير',
      'ar_already_have_account': 'لديك حساب بالفعل؟',
      'ar_dont_have_account': 'ليس لديك حساب؟',
      'ar_today_sessions': 'جلسات اليوم',
      'ar_online_time': 'وقت الاتصال',
      'ar_earnings': 'الأرباح',
      'ar_avg_rating': 'متوسط التقييم',
      'ar_dashboard': 'لوحة التحكم',
      'ar_type_message': 'اكتب رسالة...',
      'ar_session_timer': 'مؤقت الجلسة',
      'ar_total_cost': 'التكلفة الإجمالية',
      'ar_end_session': 'إنهاء الجلسة',
      'ar_session_ended': 'انتهت الجلسة',
      'ar_rate_expert': 'قيم الخبير',
      'ar_add_comment': 'إضافة تعليق (اختياري)',
      'ar_share_experience': 'شارك تجربتك مع هذا الخبير...',
      'ar_skip': 'تخطي',
      'ar_submit_review': 'إرسال المراجعة',
      'ar_review_submitted': 'شكراً لك على مراجعتك!',
      'ar_review_error': 'فشل في إرسال المراجعة. يرجى المحاولة مرة أخرى.',
      'ar_duration': 'المدة',
      'ar_write_review': 'اكتب مراجعة',
      'ar_submit_review': 'إرسال المراجعة',
      'ar_payment_method': 'طريقة الدفع',
      'ar_pay_per_minute': 'دفع بالدقيقة',
      'ar_pay_per_session': 'دفع بالجلسة',
      'ar_start_session': 'بدء الجلسة',
      'ar_minutes': 'دقائق',
      'ar_hours': 'ساعات',
      'ar_home': 'الرئيسية',
      'ar_recent_chats': 'المحادثات الأخيرة',
      'ar_view_all': 'عرض الكل',
      'ar_available_experts': 'الخبراء المتاحون',
      'ar_clear_filters': 'مسح المرشحات',
      'ar_no_experts_found': 'لم يتم العثور على خبراء',
      'ar_days_ago': 'منذ {days} أيام',
      'ar_hours_ago': 'منذ {hours} ساعات',
      'ar_minutes_ago': 'منذ {minutes} دقائق',
      'ar_just_now': 'الآن',
      'ar_subcategories': 'الفئات الفرعية',
      'ar_select_subcategory': 'اختر فئة فرعية',
      'ar_show_all': 'إظهار الكل',
    };
  }

  static Map<ExpertCategory, List<String>> getCategorySubcategories() {
    return {
      ExpertCategory.doctor: [
        'General Medicine',
        'Cardiology',
        'Pediatrics',
        'Dermatology',
        'Orthopedics'
      ],
      ExpertCategory.lawyer: [
        'Corporate Law',
        'Family Law',
        'Criminal Law',
        'Real Estate Law',
        'Immigration Law'
      ],
      ExpertCategory.lifeCoach: [
        'Career Coaching',
        'Relationship Coaching',
        'Health & Wellness',
        'Personal Development',
        'Goal Setting'
      ],
      ExpertCategory.businessConsultant: [
        'Strategy Consulting',
        'Financial Planning',
        'Marketing & Sales',
        'Operations Management',
        'Startup Consulting'
      ],
      ExpertCategory.therapist: [
        'Anxiety & Depression',
        'Relationship Therapy',
        'Child Psychology',
        'Trauma Therapy',
        'Addiction Counseling'
      ],
      ExpertCategory.technician: [
        'IT Support',
        'Network Setup',
        'Software Installation',
        'Hardware Repair',
        'System Maintenance'
      ],
      ExpertCategory.religion: [
        'Islam',
        'Christianity',
        'Judaism',
        'Buddhism',
        'Hinduism'
      ]
    };
  }

  static Map<ExpertCategory, List<String>> getCategorySubcategoriesArabic() {
    return {
      ExpertCategory.doctor: [
        'الطب العام',
        'أمراض القلب',
        'طب الأطفال',
        'الأمراض الجلدية',
        'جراحة العظام'
      ],
      ExpertCategory.lawyer: [
        'القانون التجاري',
        'قانون الأسرة',
        'القانون الجنائي',
        'قانون العقارات',
        'قانون الهجرة'
      ],
      ExpertCategory.lifeCoach: [
        'التدريب المهني',
        'تدريب العلاقات',
        'الصحة والعافية',
        'التطوير الشخصي',
        'وضع الأهداف'
      ],
      ExpertCategory.businessConsultant: [
        'الاستشارات الاستراتيجية',
        'التخطيط المالي',
        'التسويق والمبيعات',
        'إدارة العمليات',
        'استشارات الشركات الناشئة'
      ],
      ExpertCategory.therapist: [
        'القلق والاكتئاب',
        'العلاج النفسي للعلاقات',
        'علم نفس الطفل',
        'علاج الصدمات',
        'علاج الإدمان'
      ],
      ExpertCategory.technician: [
        'الدعم التقني',
        'إعداد الشبكات',
        'تثبيت البرامج',
        'إصلاح الأجهزة',
        'صيانة الأنظمة'
      ],
      ExpertCategory.religion: [
        'الإسلام',
        'المسيحية',
        'اليهودية',
        'البوذية',
        'الهندوسية'
      ]
    };
  }

  static List<Business> getBusinesses() {
    return [
      Business(
        id: 'biz1',
        name: 'TechCorp Solutions',
        industry: BusinessIndustry.technology,
        contactEmail: 'admin@techcorp.com',
        assignedExpertIds: [],
        monthlySpending: 1250.0,
        totalSessions: 24,
        createdAt: DateTime.now().subtract(const Duration(days: 30)),
        businessCode: 'BIZ-123456',
        verificationStatus: VerificationStatus.verified,
        description: 'Leading technology consulting firm specializing in digital transformation and IT solutions.',
        website: 'https://techcorp.com',
        country: 'United States',
        verificationAttachments: [
          {
            'title': 'Business License',
            'description': 'Official business license document',
            'type': 'Document',
            'url': 'https://example.com/business-license.pdf'
          },
          {
            'title': 'Tax Registration',
            'description': 'Tax registration certificate',
            'type': 'Document',
            'url': 'https://example.com/tax-registration.pdf'
          },
          {
            'title': 'Company Profile',
            'description': 'Official company profile and certifications',
            'type': 'Document',
            'url': 'https://example.com/company-profile.pdf'
          }
        ],
      ),
      Business(
        id: 'biz2',
        name: 'HealthFirst Medical',
        industry: BusinessIndustry.healthcare,
        contactEmail: 'info@healthfirst.com',
        assignedExpertIds: [],
        monthlySpending: 800.0,
        totalSessions: 15,
        createdAt: DateTime.now().subtract(const Duration(days: 20)),
        businessCode: 'BIZ-789012',
        verificationStatus: VerificationStatus.underReview,
        description: 'Comprehensive healthcare services with a focus on preventive care and wellness.',
        website: 'https://healthfirst.com',
        country: 'Canada',
        verificationAttachments: [
          {
            'title': 'Medical License',
            'description': 'Healthcare facility license',
            'type': 'Document',
            'url': 'https://example.com/medical-license.pdf'
          },
          {
            'title': 'Insurance Certificate',
            'description': 'Professional liability insurance',
            'type': 'Document',
            'url': 'https://example.com/insurance.pdf'
          }
        ],
      ),
      Business(
        id: 'biz3',
        name: 'Legal Solutions Inc',
        industry: BusinessIndustry.legal,
        contactEmail: 'contact@legalsolutions.com',
        assignedExpertIds: [],
        monthlySpending: 0.0,
        totalSessions: 0,
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        businessCode: '',
        verificationStatus: VerificationStatus.unverified,
        description: 'Full-service law firm providing corporate and individual legal services.',
        website: null,
        country: 'United Kingdom',
        verificationAttachments: [
          {
            'title': 'Bar Association License',
            'description': 'Law firm registration with bar association',
            'type': 'Document',
            'url': 'https://example.com/bar-license.pdf'
          },
          {
            'title': 'Business Registration',
            'description': 'Official business registration document',
            'type': 'Document',
            'url': 'https://example.com/business-registration.pdf'
          }
        ],
      ),
    ];
  }
}